package br.com.torrentzfilmes.app;

//import br.com.torrentzfilmes.app.TelaContinente;
import javax.swing.JOptionPane;

/**
 *
 * @author Aires Ribeiro
 */
public class MenuPrincipalApp extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public MenuPrincipalApp() {
        setExtendedState(MAXIMIZED_BOTH);
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPaneTorrentz = new javax.swing.JDesktopPane();
        jMenuBarTelaPrincipal = new javax.swing.JMenuBar();
        jMenuOperacoes = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemSair = new javax.swing.JMenuItem();
        jMenuCadastros = new javax.swing.JMenu();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItemCadUsuarios = new javax.swing.JMenuItem();
        jMenuRelatorios = new javax.swing.JMenu();
        jMenuItemRelatorioDeCategorias = new javax.swing.JMenuItem();
        jMenuItemRelatorioDeContratos = new javax.swing.JMenuItem();
        jMenuItemRelatorioDeFilmes = new javax.swing.JMenuItem();
        jMenuItemRelatorioDePlanos = new javax.swing.JMenuItem();
        jMenuItemRelatorioDeUsuarios = new javax.swing.JMenuItem();
        jMenuItemFilmesVisualizados = new javax.swing.JMenuItem();
        jMenuFerramentas = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Torrentz Filmes");

        javax.swing.GroupLayout jDesktopPaneTorrentzLayout = new javax.swing.GroupLayout(jDesktopPaneTorrentz);
        jDesktopPaneTorrentz.setLayout(jDesktopPaneTorrentzLayout);
        jDesktopPaneTorrentzLayout.setHorizontalGroup(
            jDesktopPaneTorrentzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 691, Short.MAX_VALUE)
        );
        jDesktopPaneTorrentzLayout.setVerticalGroup(
            jDesktopPaneTorrentzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 624, Short.MAX_VALUE)
        );

        jMenuOperacoes.setText("Operação");
        jMenuOperacoes.add(jSeparator1);

        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenuOperacoes.add(jMenuItemSair);

        jMenuBarTelaPrincipal.add(jMenuOperacoes);

        jMenuCadastros.setText("Cadastros");

        jMenuItem12.setText("Categoria");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItem12);

        jMenuItem1.setText("Filmes");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItem1);

        jMenuItem2.setText("Planos");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItem2);

        jMenuItemCadUsuarios.setText("Usuários");
        jMenuItemCadUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadUsuariosActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemCadUsuarios);

        jMenuBarTelaPrincipal.add(jMenuCadastros);

        jMenuRelatorios.setText("Relatórios");
        jMenuRelatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRelatoriosActionPerformed(evt);
            }
        });

        jMenuItemRelatorioDeCategorias.setText("Categorias");
        jMenuItemRelatorioDeCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRelatorioDeCategoriasActionPerformed(evt);
            }
        });
        jMenuRelatorios.add(jMenuItemRelatorioDeCategorias);

        jMenuItemRelatorioDeContratos.setText("Contratos");
        jMenuItemRelatorioDeContratos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRelatorioDeContratosActionPerformed(evt);
            }
        });
        jMenuRelatorios.add(jMenuItemRelatorioDeContratos);

        jMenuItemRelatorioDeFilmes.setText("Filmes");
        jMenuItemRelatorioDeFilmes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRelatorioDeFilmesActionPerformed(evt);
            }
        });
        jMenuRelatorios.add(jMenuItemRelatorioDeFilmes);

        jMenuItemRelatorioDePlanos.setText("Planos");
        jMenuItemRelatorioDePlanos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRelatorioDePlanosActionPerformed(evt);
            }
        });
        jMenuRelatorios.add(jMenuItemRelatorioDePlanos);

        jMenuItemRelatorioDeUsuarios.setText("Usuários");
        jMenuItemRelatorioDeUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRelatorioDeUsuariosActionPerformed(evt);
            }
        });
        jMenuRelatorios.add(jMenuItemRelatorioDeUsuarios);

        jMenuItemFilmesVisualizados.setText("Filmes Visualizados");
        jMenuItemFilmesVisualizados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFilmesVisualizadosActionPerformed(evt);
            }
        });
        jMenuRelatorios.add(jMenuItemFilmesVisualizados);

        jMenuBarTelaPrincipal.add(jMenuRelatorios);

        jMenuFerramentas.setText("Ferramentas");
        jMenuFerramentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuFerramentasActionPerformed(evt);
            }
        });
        jMenuBarTelaPrincipal.add(jMenuFerramentas);

        setJMenuBar(jMenuBarTelaPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPaneTorrentz)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPaneTorrentz)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(719, 698));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuFerramentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuFerramentasActionPerformed
    }//GEN-LAST:event_jMenuFerramentasActionPerformed

    //Sair do programa
    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);                                 //Sai do sistema fechando a tela
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        // TODO add your handling code here:
        try {
            new CategoriaApp(this, true).setVisible(true);
            this.setVisible(true);

        } catch (Exception e) {
        }
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        try {
            new PlanoApp(this, true).setVisible(true);
            this.setVisible(true);

        } catch (Exception e) {
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        try {
            new FilmeApp(this, true).setVisible(true);
            this.setVisible(true);
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());

        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItemCadUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadUsuariosActionPerformed
        // TODO add your handling code here:
        try {
            new UsuarioApp(this, true).setVisible(true);
            this.setVisible(true);
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        }

    }//GEN-LAST:event_jMenuItemCadUsuariosActionPerformed

    private void jMenuItemRelatorioDeContratosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRelatorioDeContratosActionPerformed
        // TODO add your handling code here:
        try {
            new RelatorioDeContratosApp(this, true).setVisible(true);
            this.setVisible(true);
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        }
    }//GEN-LAST:event_jMenuItemRelatorioDeContratosActionPerformed

    private void jMenuItemRelatorioDePlanosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRelatorioDePlanosActionPerformed
        // TODO add your handling code here:
        new RelatorioDePlanosApp(this, true).setVisible(true);
        this.setVisible(true);
    }//GEN-LAST:event_jMenuItemRelatorioDePlanosActionPerformed

    private void jMenuItemRelatorioDeFilmesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRelatorioDeFilmesActionPerformed
        // TODO add your handling code here:
        new RelatorioDeFilmesApp(this, true).setVisible(true);
        this.setVisible(true);
    }//GEN-LAST:event_jMenuItemRelatorioDeFilmesActionPerformed

    private void jMenuItemRelatorioDeCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRelatorioDeCategoriasActionPerformed
        // TODO add your handling code here:
        new RelatorioDeCategoriaApp(this, true).setVisible(true);
        this.setVisible(true);
    }//GEN-LAST:event_jMenuItemRelatorioDeCategoriasActionPerformed

    private void jMenuRelatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRelatoriosActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenuRelatoriosActionPerformed

    private void jMenuItemRelatorioDeUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRelatorioDeUsuariosActionPerformed
        // TODO add your handling code here:
        new RelatorioDeUsuariosApp(this, true).setVisible(true);
        this.setVisible(true);
    }//GEN-LAST:event_jMenuItemRelatorioDeUsuariosActionPerformed

    private void jMenuItemFilmesVisualizadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFilmesVisualizadosActionPerformed
        // TODO add your handling code here:
        new RelatorioDeFilmesVisualizadosApp(this, true).setVisible(true);
        this.setVisible(true);
    }//GEN-LAST:event_jMenuItemFilmesVisualizadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {                                      //alterar para que os botoes fiquem no padrão Windows
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipalApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPaneTorrentz;
    private javax.swing.JMenuBar jMenuBarTelaPrincipal;
    private javax.swing.JMenu jMenuCadastros;
    private javax.swing.JMenu jMenuFerramentas;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItemCadUsuarios;
    private javax.swing.JMenuItem jMenuItemFilmesVisualizados;
    private javax.swing.JMenuItem jMenuItemRelatorioDeCategorias;
    private javax.swing.JMenuItem jMenuItemRelatorioDeContratos;
    private javax.swing.JMenuItem jMenuItemRelatorioDeFilmes;
    private javax.swing.JMenuItem jMenuItemRelatorioDePlanos;
    private javax.swing.JMenuItem jMenuItemRelatorioDeUsuarios;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenu jMenuOperacoes;
    private javax.swing.JMenu jMenuRelatorios;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
