/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.torrentzfilmes.app;

import br.com.torrentzfilmes.bll.PlanoBll;
import br.com.torrentzfilmes.model.Plano;
import java.math.BigDecimal;
import java.util.List;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author roger
 */
public class PlanoApp extends javax.swing.JDialog {

    PlanoBll plaBll = new PlanoBll();
    Plano plano;

    /**
     * Creates new form PlanoApp
     */
    public PlanoApp(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Locale.setDefault(Locale.US);
        jButtonExcluir.setEnabled(false);
        jTextFieldDescPlano.requestFocus();

    }

    private void imprimirDadosPlanos(List<Plano> listaDePlanos) throws Exception {
        DefaultTableModel model = (DefaultTableModel) jTablePlano.getModel();
        model.setNumRows(0);
        plaBll.ordenaListaPlanos(listaDePlanos);
        for (int pos = 0; pos < listaDePlanos.size(); pos++) {
            String[] linha = new String[4];
            Plano plano = listaDePlanos.get(pos);
            linha[0] = "" + plano.getId();
            linha[1] = plano.getDescricao().toUpperCase();
            linha[2] = "" + plano.getAcessoSimultaneo();
            linha[3] = String.format("%.2f", plano.getPreco());
            model.addRow(linha);
        }
        jTextFieldQuantRegistros.setText(listaDePlanos.size() + "");
    }

    public void limpaCampos() {
        jTextFieldCodigo.setText("");
        jTextFieldDescPlano.setText("");
        jTextFieldQtdeAcessoSimultaneos.setText("");
        jTextFieldValorDoPlano.setText("");
        jTextFieldQuantRegistros.setText("");
        jButtonExcluir.setEnabled(false);
        jButtonSalvar.setLabel("Salvar");
        jTextFieldDescPlano.requestFocus();
    }

    public void preencherCampos(int id) {
        try {
            if (id > 0) {
                plano = plaBll.getConsultaPorId(id);
                jTextFieldCodigo.setText(id + "");
                jTextFieldDescPlano.setText(plano.getDescricao());
                jTextFieldQtdeAcessoSimultaneos.setText(plano.getAcessoSimultaneo() + "");
                jTextFieldValorDoPlano.setText(String.format("%.2f", plano.getPreco()));

                jButtonSalvar.setLabel("Editar");
                jButtonExcluir.setEnabled(true);
                jTextFieldDescPlano.requestFocus();
            } else {
                jButtonSalvar.setLabel("Salvar");
            }

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Atenção mouseclicked!"
                    + erro.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCadPlanos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldDescPlano = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldQtdeAcessoSimultaneos = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldValorDoPlano = new javax.swing.JTextField();
        jButtonSalvar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonConsultar = new javax.swing.JButton();
        jButtonNovo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePlano = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldQuantRegistros = new javax.swing.JTextField();
        jButtonFechar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Manutenção de cadastro de planos");
        setResizable(false);

        jPanelCadPlanos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Código:");

        jLabel2.setText("Descrição:");

        jLabel3.setText("Quant. de Acessos Simultânes:");

        jLabel4.setText("Preço:  R$ ");

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonConsultar.setText("Consultar");
        jButtonConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarActionPerformed(evt);
            }
        });

        jButtonNovo.setText("Novo");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });

        jTablePlano.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Descrição", "Qtde. Acesso Simult.", "Valor do Plano"
            }
        ));
        jTablePlano.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTablePlanoMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTablePlano);
        if (jTablePlano.getColumnModel().getColumnCount() > 0) {
            jTablePlano.getColumnModel().getColumn(0).setMinWidth(50);
            jTablePlano.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTablePlano.getColumnModel().getColumn(0).setMaxWidth(50);
            jTablePlano.getColumnModel().getColumn(2).setMinWidth(80);
            jTablePlano.getColumnModel().getColumn(2).setPreferredWidth(80);
            jTablePlano.getColumnModel().getColumn(2).setMaxWidth(80);
        }

        jLabel5.setText("Quant. de Registros:");

        jButtonFechar.setText("Fechar");
        jButtonFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCadPlanosLayout = new javax.swing.GroupLayout(jPanelCadPlanos);
        jPanelCadPlanos.setLayout(jPanelCadPlanosLayout);
        jPanelCadPlanosLayout.setHorizontalGroup(
            jPanelCadPlanosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadPlanosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCadPlanosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE)
                    .addGroup(jPanelCadPlanosLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldQuantRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonConsultar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonFechar))
                    .addGroup(jPanelCadPlanosLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldDescPlano))
                    .addGroup(jPanelCadPlanosLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldQtdeAcessoSimultaneos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jLabel4)
                        .addGap(7, 7, 7)
                        .addComponent(jTextFieldValorDoPlano)))
                .addContainerGap())
        );
        jPanelCadPlanosLayout.setVerticalGroup(
            jPanelCadPlanosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadPlanosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCadPlanosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldDescPlano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanelCadPlanosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldQtdeAcessoSimultaneos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldValorDoPlano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                .addGap(27, 27, 27)
                .addGroup(jPanelCadPlanosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldQuantRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonFechar)
                    .addComponent(jButtonSalvar)
                    .addComponent(jButtonExcluir)
                    .addComponent(jButtonConsultar)
                    .addComponent(jButtonNovo))
                .addGap(13, 13, 13))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelCadPlanos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelCadPlanos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        // TODO add your handling code here:
        if (jTextFieldDescPlano.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "O campo descrição "
                    + " é obrigatório  o preenchimento!\n");
        } else if (jTextFieldQtdeAcessoSimultaneos.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "O campo quant. de "
                    + "acesso simultâneos é obrigatório o preenchimento!\n");
        } else if (jTextFieldValorDoPlano.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "O campo preço é"
                    + " obrigatório o preenchimento!\n");
        } else {
            try {
                int quantAcessos = Integer.parseInt(jTextFieldQtdeAcessoSimultaneos.getText());
                String descricao = jTextFieldDescPlano.getText();
                BigDecimal preco = new BigDecimal(jTextFieldValorDoPlano.getText());
                plano = new Plano(quantAcessos, descricao, preco);

                if (jButtonSalvar.getLabel().equals("Salvar")) {
                    plaBll.adicionarPlano(plano);
                } else {
                    int id = Integer.parseInt(jTextFieldCodigo.getText());
                    plano = new Plano(id, quantAcessos, descricao, preco);
                    plaBll.alterarPlano(plano);
                }
                limpaCampos();

            } catch (Exception erro) {
                JOptionPane.showMessageDialog(null, erro.getMessage());
            }
        }
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        // TODO add your handling code here:
        try {
            plaBll.excluirPlano(plaBll.getConsultaPorId(plano.getId()));
            imprimirDadosPlanos(plaBll.getConsultaPlanos());
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        }
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarActionPerformed
        // TODO add your handling code here:
        try {
            imprimirDadosPlanos(plaBll.pesquisarPlano(jTextFieldDescPlano.getText()));
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        }
    }//GEN-LAST:event_jButtonConsultarActionPerformed

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        // TODO add your handling code here:
        try {
            limpaCampos();
            DefaultTableModel model = (DefaultTableModel) jTablePlano.getModel();
            model.setNumRows(0);

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        }
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonFecharActionPerformed

    private void jTablePlanoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePlanoMouseReleased
        // TODO add your handling code here:
        try {
            int linha = jTablePlano.getSelectedRow();
            Integer codigo = Integer.parseInt(jTablePlano.getValueAt(linha, 0).toString());
            preencherCampos(codigo);
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        }
    }//GEN-LAST:event_jTablePlanoMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlanoApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlanoApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlanoApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlanoApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PlanoApp dialog = new PlanoApp(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConsultar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonFechar;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanelCadPlanos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePlano;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldDescPlano;
    private javax.swing.JTextField jTextFieldQtdeAcessoSimultaneos;
    private javax.swing.JTextField jTextFieldQuantRegistros;
    private javax.swing.JTextField jTextFieldValorDoPlano;
    // End of variables declaration//GEN-END:variables
}
