/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.torrentzfilmes.app;

import br.com.torrentzfilmes.bll.ContratoBll;
import br.com.torrentzfilmes.model.Contrato;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author roger
 */
public class RelatorioDeContratosApp extends javax.swing.JDialog {

    ContratoBll contBll = new ContratoBll();

    /**
     * Creates new form RelatorioDeContratos
     */
    public RelatorioDeContratosApp(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public void imprimirRelatorioDeContratos(List<Contrato> listaContratos) throws Exception {
        DefaultTableModel model = (DefaultTableModel) jTableRelatorioContratos.getModel();
        model.setNumRows(0);
        contBll.ordenaListaContratos(listaContratos);
        for (int pos = 0; pos < listaContratos.size(); pos++) {
            String[] linha = new String[13];
            Contrato cont = listaContratos.get(pos);
            linha[0] = cont.getId() + "";
            linha[1] = cont.getStatus().name().toUpperCase();
            linha[2] = cont.getUsuario().getNome().toUpperCase();
            linha[3] = cont.getUsuario().getCpf();
            linha[4] = cont.getUsuario().getEmail();
            linha[5] = cont.getUsuario().getPercCupom() + " %";
            SimpleDateFormat dataCupom = new SimpleDateFormat("dd/MM/yyyy");
            linha[6] = dataCupom.format(cont.getUsuario().getDataCupom());
            linha[7] = cont.getUsuario().getPerfil().toString();
            SimpleDateFormat dataInicial = new SimpleDateFormat("dd/MM/yyyy");
            linha[8] = dataInicial.format(cont.getInicio());
            SimpleDateFormat dataFinal = new SimpleDateFormat("dd/MM/yyyy");
            linha[9] = dataFinal.format(cont.getFim());
            linha[10] = cont.getPlano().getDescricao().toUpperCase();
            linha[11] = cont.getPlano().getAcessoSimultaneo() + "";
            linha[12] = String.format("%.2f", cont.getPlano().getPreco());
            model.addRow(linha);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelRelatorioDeContratos = new javax.swing.JPanel();
        jButtonPesquisarContratos = new javax.swing.JButton();
        jTextFieldDigitarDadosParaPesquisa = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableRelatorioContratos = new javax.swing.JTable();
        jButtonFechar = new javax.swing.JButton();
        jButtonListarRelatorioDeContratos = new javax.swing.JButton();
        jButtonNovoContrato = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Relatório de Contratos Torrentz Filmes");
        setResizable(false);

        jPanelRelatorioDeContratos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButtonPesquisarContratos.setText("Pesquisar Contratos");
        jButtonPesquisarContratos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarContratosActionPerformed(evt);
            }
        });

        jTextFieldDigitarDadosParaPesquisa.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldDigitarDadosParaPesquisa.setText("Para pesquisar Digite aqui o nome do usuário ou o cpf");
        jTextFieldDigitarDadosParaPesquisa.setDisabledTextColor(new java.awt.Color(51, 51, 51));

        jTableRelatorioContratos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Status", "Nome do Usuário", " Cpf", "Email", "Perc. Cupom", "Data Cupom", "Perfil do Usuário", "Início Contrato", "Fim Contrato", "Tipo do Plano", "Acessos Simult.", "Preço do Plano"
            }
        ));
        jScrollPane1.setViewportView(jTableRelatorioContratos);
        if (jTableRelatorioContratos.getColumnModel().getColumnCount() > 0) {
            jTableRelatorioContratos.getColumnModel().getColumn(0).setMinWidth(50);
            jTableRelatorioContratos.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTableRelatorioContratos.getColumnModel().getColumn(0).setMaxWidth(50);
            jTableRelatorioContratos.getColumnModel().getColumn(1).setMinWidth(60);
            jTableRelatorioContratos.getColumnModel().getColumn(1).setPreferredWidth(60);
            jTableRelatorioContratos.getColumnModel().getColumn(1).setMaxWidth(60);
            jTableRelatorioContratos.getColumnModel().getColumn(3).setMinWidth(85);
            jTableRelatorioContratos.getColumnModel().getColumn(3).setPreferredWidth(85);
            jTableRelatorioContratos.getColumnModel().getColumn(3).setMaxWidth(85);
            jTableRelatorioContratos.getColumnModel().getColumn(4).setMinWidth(150);
            jTableRelatorioContratos.getColumnModel().getColumn(4).setPreferredWidth(150);
            jTableRelatorioContratos.getColumnModel().getColumn(4).setMaxWidth(150);
            jTableRelatorioContratos.getColumnModel().getColumn(5).setMinWidth(80);
            jTableRelatorioContratos.getColumnModel().getColumn(5).setPreferredWidth(80);
            jTableRelatorioContratos.getColumnModel().getColumn(5).setMaxWidth(80);
            jTableRelatorioContratos.getColumnModel().getColumn(6).setMinWidth(80);
            jTableRelatorioContratos.getColumnModel().getColumn(6).setPreferredWidth(80);
            jTableRelatorioContratos.getColumnModel().getColumn(6).setMaxWidth(80);
            jTableRelatorioContratos.getColumnModel().getColumn(7).setMinWidth(90);
            jTableRelatorioContratos.getColumnModel().getColumn(7).setPreferredWidth(90);
            jTableRelatorioContratos.getColumnModel().getColumn(7).setMaxWidth(90);
            jTableRelatorioContratos.getColumnModel().getColumn(8).setMinWidth(80);
            jTableRelatorioContratos.getColumnModel().getColumn(8).setPreferredWidth(80);
            jTableRelatorioContratos.getColumnModel().getColumn(8).setMaxWidth(80);
            jTableRelatorioContratos.getColumnModel().getColumn(9).setMinWidth(80);
            jTableRelatorioContratos.getColumnModel().getColumn(9).setPreferredWidth(80);
            jTableRelatorioContratos.getColumnModel().getColumn(9).setMaxWidth(80);
            jTableRelatorioContratos.getColumnModel().getColumn(10).setMinWidth(90);
            jTableRelatorioContratos.getColumnModel().getColumn(10).setPreferredWidth(90);
            jTableRelatorioContratos.getColumnModel().getColumn(10).setMaxWidth(90);
            jTableRelatorioContratos.getColumnModel().getColumn(11).setMinWidth(90);
            jTableRelatorioContratos.getColumnModel().getColumn(11).setPreferredWidth(90);
            jTableRelatorioContratos.getColumnModel().getColumn(11).setMaxWidth(90);
            jTableRelatorioContratos.getColumnModel().getColumn(12).setMinWidth(90);
            jTableRelatorioContratos.getColumnModel().getColumn(12).setPreferredWidth(90);
            jTableRelatorioContratos.getColumnModel().getColumn(12).setMaxWidth(90);
        }

        jButtonFechar.setText("Fechar");
        jButtonFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharActionPerformed(evt);
            }
        });

        jButtonListarRelatorioDeContratos.setText("Listar");
        jButtonListarRelatorioDeContratos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarRelatorioDeContratosActionPerformed(evt);
            }
        });

        jButtonNovoContrato.setText("Nova consulta");

        javax.swing.GroupLayout jPanelRelatorioDeContratosLayout = new javax.swing.GroupLayout(jPanelRelatorioDeContratos);
        jPanelRelatorioDeContratos.setLayout(jPanelRelatorioDeContratosLayout);
        jPanelRelatorioDeContratosLayout.setHorizontalGroup(
            jPanelRelatorioDeContratosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRelatorioDeContratosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelRelatorioDeContratosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanelRelatorioDeContratosLayout.createSequentialGroup()
                        .addComponent(jButtonPesquisarContratos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldDigitarDadosParaPesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, 1098, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRelatorioDeContratosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonNovoContrato)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonListarRelatorioDeContratos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonFechar)))
                .addContainerGap())
        );
        jPanelRelatorioDeContratosLayout.setVerticalGroup(
            jPanelRelatorioDeContratosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRelatorioDeContratosLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanelRelatorioDeContratosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPesquisarContratos)
                    .addComponent(jTextFieldDigitarDadosParaPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanelRelatorioDeContratosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonFechar)
                    .addComponent(jButtonListarRelatorioDeContratos)
                    .addComponent(jButtonNovoContrato))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelRelatorioDeContratos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelRelatorioDeContratos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonListarRelatorioDeContratosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarRelatorioDeContratosActionPerformed
        // TODO add your handling code here:
        try {
            imprimirRelatorioDeContratos(contBll.getConsultaContratos());
            
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        }
    }//GEN-LAST:event_jButtonListarRelatorioDeContratosActionPerformed

    private void jButtonFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonFecharActionPerformed

    private void jButtonPesquisarContratosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarContratosActionPerformed
        // TODO add your handling code here:
        try {
            imprimirRelatorioDeContratos(contBll.pesquisarContrato(jTextFieldDigitarDadosParaPesquisa.getText()));
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        }
    }//GEN-LAST:event_jButtonPesquisarContratosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RelatorioDeContratosApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RelatorioDeContratosApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RelatorioDeContratosApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RelatorioDeContratosApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RelatorioDeContratosApp dialog = new RelatorioDeContratosApp(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFechar;
    private javax.swing.JButton jButtonListarRelatorioDeContratos;
    private javax.swing.JButton jButtonNovoContrato;
    private javax.swing.JButton jButtonPesquisarContratos;
    private javax.swing.JPanel jPanelRelatorioDeContratos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableRelatorioContratos;
    private javax.swing.JTextField jTextFieldDigitarDadosParaPesquisa;
    // End of variables declaration//GEN-END:variables
}
