/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.torrentzfilmes.app;

import br.com.torrentzfilmes.bll.VisualizadoBll;
import br.com.torrentzfilmes.model.Visualizado;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author roger
 */
public class RelatorioDeFilmesVisualizadosApp extends javax.swing.JDialog {

    VisualizadoBll visuBll;
    Visualizado visual;

    /**
     * Creates new form RelatorioDeFilmesVisualizadosApp
     */
    public RelatorioDeFilmesVisualizadosApp(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        visuBll = new VisualizadoBll();

    }

    private void imprimirFilmesVisualizados(List<Visualizado> lista) throws Exception {
        DefaultTableModel model = (DefaultTableModel) jTableFilmesVisualizados.getModel();
        model.setNumRows(0);
        for (int pos = 0; pos < lista.size(); pos++) {
            String[] linha = new String[5];
            visual = lista.get(pos);
            linha[0] = "" + visual.getId();
            SimpleDateFormat dataFormatada = new SimpleDateFormat("dd/MM/yyyy");
            linha[1] = dataFormatada.format(visual.getDataVisualizacao());
            linha[2] = visual.getUsuario().getNome().toUpperCase();
            linha[3] = visual.getFilme().getTitulo().toUpperCase();
            if (visual.isCompleto() == false) {
                linha[4] = "Vis.Incompleta";
            } else {
                linha[4] = "Vis.Completa";
            }
            model.addRow(linha);
        }
        jTextFieldQuantRegistros.setText(lista.size() + "");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFilmesVisualizados = new javax.swing.JPanel();
        jButtonFechar = new javax.swing.JButton();
        jButtonListarFilmesVisualizados = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableFilmesVisualizados = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldQuantRegistros = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Relatório de Filmes Visualizados - Torrentz Filmes");
        setAutoRequestFocus(false);
        setResizable(false);

        jPanelFilmesVisualizados.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButtonFechar.setText("Fechar");
        jButtonFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharActionPerformed(evt);
            }
        });

        jButtonListarFilmesVisualizados.setText("Listar");
        jButtonListarFilmesVisualizados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarFilmesVisualizadosActionPerformed(evt);
            }
        });

        jTableFilmesVisualizados.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTableFilmesVisualizados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cód.", "Data da Visualização", "Nome do Usuário", "Título do Filme", "Vis. Completo ?"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableFilmesVisualizados);
        if (jTableFilmesVisualizados.getColumnModel().getColumnCount() > 0) {
            jTableFilmesVisualizados.getColumnModel().getColumn(0).setMinWidth(50);
            jTableFilmesVisualizados.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTableFilmesVisualizados.getColumnModel().getColumn(0).setMaxWidth(50);
            jTableFilmesVisualizados.getColumnModel().getColumn(1).setMinWidth(110);
            jTableFilmesVisualizados.getColumnModel().getColumn(1).setPreferredWidth(110);
            jTableFilmesVisualizados.getColumnModel().getColumn(1).setMaxWidth(110);
            jTableFilmesVisualizados.getColumnModel().getColumn(4).setMinWidth(100);
            jTableFilmesVisualizados.getColumnModel().getColumn(4).setPreferredWidth(100);
            jTableFilmesVisualizados.getColumnModel().getColumn(4).setMaxWidth(100);
        }

        jLabel1.setText("Quant. Registros");

        javax.swing.GroupLayout jPanelFilmesVisualizadosLayout = new javax.swing.GroupLayout(jPanelFilmesVisualizados);
        jPanelFilmesVisualizados.setLayout(jPanelFilmesVisualizadosLayout);
        jPanelFilmesVisualizadosLayout.setHorizontalGroup(
            jPanelFilmesVisualizadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFilmesVisualizadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFilmesVisualizadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFilmesVisualizadosLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldQuantRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonListarFilmesVisualizados)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonFechar)
                        .addGap(16, 16, 16))
                    .addGroup(jPanelFilmesVisualizadosLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 989, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanelFilmesVisualizadosLayout.setVerticalGroup(
            jPanelFilmesVisualizadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFilmesVisualizadosLayout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(jPanelFilmesVisualizadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonFechar)
                    .addComponent(jButtonListarFilmesVisualizados)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldQuantRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelFilmesVisualizados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelFilmesVisualizados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonFecharActionPerformed

    private void jButtonListarFilmesVisualizadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarFilmesVisualizadosActionPerformed
        // TODO add your handling code here:
        try {
            imprimirFilmesVisualizados(visuBll.getConsultaVisualizados());
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        }
    }//GEN-LAST:event_jButtonListarFilmesVisualizadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RelatorioDeFilmesVisualizadosApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RelatorioDeFilmesVisualizadosApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RelatorioDeFilmesVisualizadosApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RelatorioDeFilmesVisualizadosApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RelatorioDeFilmesVisualizadosApp dialog = new RelatorioDeFilmesVisualizadosApp(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFechar;
    private javax.swing.JButton jButtonListarFilmesVisualizados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanelFilmesVisualizados;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableFilmesVisualizados;
    private javax.swing.JTextField jTextFieldQuantRegistros;
    // End of variables declaration//GEN-END:variables

}
